apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-nginx-hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandbox-nginx-hello
  template:
    metadata:
      labels:
        app: sandbox-nginx-hello
    spec:
      containers:
      - image: nginxdemos/nginx-hello:plain-text
        name: nginx
        ports:
        - containerPort: 80