apiVersion: v1
kind: Service
metadata:
  name: sandbox-nginx-hello-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: sandbox-nginx-hello